### ISSUE TITLE
Exception seen in Index Manager.

### ISSUE THREAD

**Issue by jeme** [dotJEM/json-index2#3]
An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/2/ROOT

Process ID: 48588

Exception: Lucene.Net.Index.IndexNotFoundException

Message: no segments* file found in SimpleFSDirectory@E:\Workspace\SSN\nsw-home\nsw\Client\NSW\APP_DATA\index lockFactory=NativeFSLockFactory@E:\Workspace\SSN\nsw-home\nsw\Client\NSW\APP_DATA\index: files: [write.lock, _a.nvm, _a.si, _a_Lucene41_0.doc, _a_Lucene41_0.pos, _a_Lucene41_0.tim, _a_Lucene41_0.tip]

StackTrace:    at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
   at DotJEM.Json.Index2.IO.IndexWriterManager.Open(IJsonIndex index)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at DotJEM.Json.Index2.Util.ResetableLazy`1.get_Value()
   at DotJEM.Json.Index2.Management.Writer.JsonIndexWriter.ThrottledCommit.Tick()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

**Comment by jeme** [comment]
An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/2/ROOT

Process ID: 14980

Exception: System.IO.IOException

Message: The process cannot access the file 'E:\Workspace\SSN\nsw-home\nsw\Client\NSW\APP_DATA\index\segments_2' because it is being used by another process.

StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Lucene.Net.Store.SimpleFSDirectory.OpenInput(String name, IOContext context)
   at Lucene.Net.Store.Directory.OpenChecksumInput(String name, IOContext context)
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFileAnonymousClass.DoBody(String segmentFileName)
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
   at DotJEM.Json.Index2.IO.IndexWriterManager.Open(IJsonIndex index)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at DotJEM.Json.Index2.Util.ResetableLazy`1.get_Value()
   at DotJEM.Json.Index2.Management.Writer.JsonIndexWriter.ThrottledCommit.Tick()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

**Comment by jeme** [comment]
An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/2/ROOT

Process ID: 73248

Exception: System.ObjectDisposedException

Message: this IndexWriter is disposed.
Object name: 'Lucene.Net.Index.IndexWriter'.

StackTrace:    at Lucene.Net.Index.IndexWriter.EnsureOpen(Boolean failIfDisposing)
   at DotJEM.Json.Index2.Management.Writer.JsonIndexWriter.ThrottledCommit.Tick()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

**Comment by jeme** [comment]
An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/2/ROOT

Process ID: 33828

Exception: Lucene.Net.Index.IndexNotFoundException

Message: no segments* file found in SimpleFSDirectory@E:\Workspace\SSN\nsw-home\nsw\Client\NSW\APP_DATA\index lockFactory=NativeFSLockFactory@E:\Workspace\SSN\nsw-home\nsw\Client\NSW\APP_DATA\index: files: [write.lock, _b.fdx, _b.fnm, _b.nvd, _b.nvm, _b.si, _b_Lucene41_0.doc, _b_Lucene41_0.pos, _b_Lucene41_0.tim, _b_Lucene41_0.tip, _c.cfe, _c.cfs, _c.si, _d.cfe, _d.cfs, _d.si, _e.cfe, _e.cfs, _e.si]

StackTrace:    at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
   at DotJEM.Json.Index2.IO.IndexWriterManager.Open(IJsonIndex index)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at DotJEM.Json.Index2.Util.ResetableLazy`1.get_Value()
   at DotJEM.Json.Index2.Management.Writer.JsonIndexWriter.ThrottledCommit.Tick()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
